# Generated by Django 5.1.4 on 2025-02-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='SubjectName',
            new_name='subjectName',
        ),
    ]
