# Generated by Django 5.1.4 on 2025-04-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_doctorprofile_clinic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='a_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='a_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='a_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
