# Generated by Django 5.1.4 on 2025-03-28 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_task'),
        ),
    ]
