# Generated by Django 5.1.4 on 2025-01-02 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
