# Generated by Django 5.1.4 on 2025-04-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_department_doctorprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.TextField(blank=True),
        ),
    ]
