# Generated by Django 5.1.4 on 2025-04-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='car_image',
        ),
    ]
